[package]
name = "vorbisfile"
version = "0.2.2"
authors = [ "Peter Marheine <peter@taricorp.net>" ]

description = "Bindings to Xiph.org libvorbisfile for Ogg Vorbis."
readme = "README.md"
repository = "https://bitbucket.org/tari/vorbisfile.rs"
license = "ISC"

[dependencies]
libc = "*"
